### ISSUE TITLE
NULL values

### ISSUE THREAD

**Issue by treadmillian** [KredytyChwilowki/MySQLToolBox#2]
The function does not appear to be able to deal with NULL values, such as: s:17:"expert_assessment";N;

Suggested fix:
`WHEN __value_type = 'N' THEN
			SET __output := '';
`

Here is a complete example:

`a:74:{s:2:"id";i:190;s:7:"user_id";i:57;s:9:"status_id";i:10;s:17:"expert_assessment";N;s:23:"no_reliable_information";N;s:11:"scheme_name";s:133:"Brussels - Alternative financing of sustainable building renovation (social green loan, third party investor, FRCE) (tertiary sector)";s:22:"scheme_name_local_lang";s:135:"Développer les mécanismes de soutien financier à la rénovation durable des bâtiments (Prêt vert social, Tiers-investisseur, FRCE)";s:24:"alternative_scheme_names";s:3:"N/A";s:18:"implementing_agent";s:0:"";s:17:"brief_description";s:443:"Third-party investor - tertiary sector
Public authorities have a role to play in encouraging energy service companies to submit interesting bids to building owners who wish to improve their building’s energy performance. The role of public authorities is to bring interested companies together, to make homogeneous calls for expressions of interest, to assist in drafting specifications and to analyse bids, all in order improve price bids.";s:20:"relevant_website_url";s:60:"http://www.measures-odyssee-mure.eu/output2_te.asp?Cod=BEL22";s:29:"implementing_agent_first_name";s:0:"";s:28:"implementing_agent_last_name";s:0:"";s:25:"implementing_agent_gender";N;s:24:"implementing_agent_email";s:0:"";s:28:"implementing_agent_telephone";s:0:"";s:33:"implementing_agent_postal_address";s:0:"";s:21:"implementation_status";i:4;s:34:"equity_financing_capital_reference";s:0:"";s:35:"equity_financing_leverage_reference";s:0:"";s:32:"debt_financing_capital_reference";s:0:"";s:33:"debt_financing_leverage_reference";s:0:"";s:36:"guarantees_design_leverage_reference";s:0:"";s:39:"guarantees_operation_leverage_reference";s:0:"";s:30:"subsidy_design_ratio_reference";s:0:"";s:33:"subsidy_operation_ratio_reference";s:0:"";s:30:"design_type_of_guarantee_other";N;s:21:"design_payment_scheme";N;s:33:"operation_type_of_guarantee_other";N;s:24:"operation_payment_scheme";N;s:22:"public_characteristics";N;s:17:"public_innovative";N;s:24:"public_scheme_name_other";N;s:23:"private_characteristics";N;s:18:"private_innovative";N;s:25:"private_scheme_name_other";N;s:27:"energy_savings_start_period";N;s:25:"energy_savings_end_period";N;s:22:"energy_savings_measure";N;s:19:"energy_savings_unit";N;s:23:"energy_savings_achieved";N;s:20:"energy_savings_years";N;s:36:"energy_savings_reference_information";s:0:"";s:26:"measures_implemented_other";s:0:"";s:14:"planned_budget";N;s:19:"size_no_of_projects";N;s:26:"size_reference_information";s:0:"";s:25:"implementation_start_year";i:2007;s:23:"implementation_end_year";N;s:20:"target_sectors_other";s:0:"";s:27:"ee_measures_supported_other";s:0:"";s:23:"final_beneficiary_other";s:0:"";s:33:"final_beneficiary_amount_targeted";N;s:18:"type_of_user_other";s:0:"";s:23:"intermediaries_involved";s:0:"";s:29:"procurement_of_intermediaries";s:0:"";s:12:"coordination";s:0:"";s:20:"eligibility_criteria";s:0:"";s:16:"project_approval";s:0:"";s:19:"associated_services";s:0:"";s:22:"motivation_and_drivers";s:0:"";s:21:"market_barriers_other";s:0:"";s:31:"interaction_with_other_policies";s:0:"";s:44:"interaction_codename_other_financial_schemes";s:0:"";s:16:"long_term_vision";s:0:"";s:11:"ets_funding";i:0;s:17:"cooperative_model";i:0;s:20:"vulnerable_consumers";i:0;s:31:"outreach_strategies_description";s:0:"";s:25:"refinancing_possibilities";s:0:"";s:34:"monitoring_verification_procedures";s:0:"";s:29:"size_of_administrative_burden";s:0:"";s:21:"implementation_burden";s:0:"";s:26:"other_relevant_information";s:0:"";}`

**Comment by warpgt** [comment]
Thanks.
Support for **Null** value has been added.
